name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # builds on versions of Node that don't require --experimental-modules nor `esm` to run ESM mocha tests.
  build-node:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12.20.0, 12.x, 14.13.0, 14.x, 15.0.0, 15.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install CLI globally
        run: npm install -g typhonjs-oclif/test-cli-modern

      - name: Run local CLI (macOS / ubuntu)
        if: ${{ matrix.os != 'windows-latest' }}
        run: ./bin/run.js test

      - name: Run local CLI (windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: cd bin/ && run.cmd test
        shell: cmd

      - name: Run NPM CLI
        run: npm run run-npm-cli

      - name: Run Global CLI
        run: testcli-modern test

      - name: Run Tests
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
